# Generated by Django 5.0.1 on 2024-02-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_no', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('bed_description', models.TextField()),
                ('bed_amount', models.FloatField()),
                ('bed_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORnumber', models.IntegerField(unique=True)),
                ('lodgerID', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('payment_time', models.TimeField()),
                ('particulars', models.CharField(max_length=200)),
                ('amount_due', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Lodger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodgerID', models.CharField(default='', max_length=50, unique=True)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('contact_number', models.IntegerField()),
                ('home_address', models.CharField(default='', max_length=100)),
                ('email_address', models.EmailField(default='', max_length=254)),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('schedule_of_last_due', models.DateField()),
                ('schedule_of_next_payment', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_code', models.CharField(max_length=50, unique=True)),
                ('reservation_date', models.DateField(auto_now_add=True)),
                ('tentative_checkin', models.DateField()),
                ('lodgerID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(default='', unique=True)),
                ('room_description', models.TextField(default='')),
                ('room_type', models.CharField(default='', max_length=20)),
                ('room_amount', models.FloatField()),
                ('room_status', models.CharField(max_length=20)),
                ('no_of_beds_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransientCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodgerID', models.IntegerField()),
                ('checkinDate', models.DateField(auto_now_add=True)),
                ('checkinTime', models.TimeField()),
            ],
        ),
    ]
