# Generated by Django 5.0.1 on 2024-03-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_room_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_no', models.IntegerField()),
                ('bed_description', models.TextField()),
                ('bed_amount', models.FloatField()),
                ('bed_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(default='', unique=True)),
                ('room_description', models.TextField(default='')),
                ('room_type', models.CharField(default='', max_length=20)),
                ('room_amount', models.FloatField()),
                ('room_status', models.CharField(max_length=20)),
                ('no_of_beds_available', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Beds',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.AlterField(
            model_name='billing',
            name='lodgerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.lodger'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='lodgerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.lodger'),
        ),
        migrations.AlterField(
            model_name='transientcheckin',
            name='lodgerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.lodger'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.room'),
        ),
        migrations.AlterField(
            model_name='room_gallery',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.room'),
        ),
    ]
