# Generated by Django 5.0.1 on 2024-03-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0003_bed_room_delete_beds_delete_rooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default='', primary_key=True, serialize=False, unique=True),
        ),
    ]
