# Generated by Django 5.0.1 on 2024-03-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_remove_room_id_alter_room_room_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='room_gallery',
        ),
    ]
