# Generated by Django 5.0.1 on 2024-03-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0005_delete_room_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
